"""Auction pricing and season scale scalar formula metadata."""

from fba.contracts.formula import ScalarFormula
from fba.formulas import scalar

FORMULAS = (
    ScalarFormula(
        "season_utility",
        "替補以上賽季效用",
        "(\\sum_c z_c-z_{replacement})G/G_{season}",
        "utility",
        ("valuation.healthy_games", "valuation.replacement_count"),
        scalar.season_utility,
        {"scores": (1.0, 2.0), "replacement": 1.0, "games": 40.0, "season_games": 80.0},
        {
            "scores": "standard deviations",
            "replacement": "standard deviations",
            "games": "games",
            "season_games": "games",
        },
    ),
    ScalarFormula(
        "dollar_scale",
        "聯盟效用金額換算",
        "(TB-Nm)/\\sum_{i\\in drafted}u_i^+",
        "currency/utility",
        (),
        scalar.dollar_scale,
        {
            "teams": 2.0,
            "budget": 100.0,
            "roster_count": 4.0,
            "minimum": 1.0,
            "positive_utilities": (1.0, 1.0, 2.0, 3.0),
        },
        {
            "teams": "teams",
            "budget": "currency/team",
            "roster_count": "players",
            "minimum": "currency/player",
            "positive_utilities": "utility",
        },
    ),
    ScalarFormula(
        "dollar_value",
        "公允價格",
        "\\mathbf1[u>0](m+uS)",
        "currency",
        (),
        scalar.dollar_value,
        {"utility": 2.0, "minimum": 1.0, "scale": 28.0},
        {"utility": "utility", "minimum": "currency", "scale": "currency/utility"},
    ),
    ScalarFormula(
        "bidder_wealth",
        "買家剩餘購買力",
        "\\operatorname{clip}((B/R-m)/\\bar{s},l,h)^e",
        "wealth multiplier",
        ("market.wealth_lower", "market.wealth_upper", "market.wealth_exponent"),
        scalar.bidder_wealth,
        {
            "budget": 30.0,
            "slots": 3.0,
            "minimum": 1.0,
            "average_surplus": 6.0,
            "lower": 0.5,
            "upper": 2.0,
            "exponent": 1.0,
        },
        {
            "budget": "currency",
            "slots": "players",
            "minimum": "currency/player",
            "average_surplus": "currency/player",
            "lower": "multiplier",
            "upper": "multiplier",
            "exponent": "dimensionless",
        },
    ),
    ScalarFormula(
        "anchor",
        "有上下界的市場錨點",
        "quote\\ge cutoff?\\operatorname{clip}(quote\\,scale,min,max):min",
        "currency",
        (),
        scalar.clipped_anchor,
        {"quote": 10.0, "scale": 2.0, "minimum": 1.0, "maximum": 15.0, "cutoff": 5.0},
        {
            "quote": "currency",
            "scale": "multiplier",
            "minimum": "currency",
            "maximum": "currency",
            "cutoff": "currency",
        },
    ),
    ScalarFormula(
        "inflation",
        "剩餘市場通膨",
        "cash/\\sum anchor",
        "multiplier",
        (),
        scalar.market_inflation,
        {"cash": 120.0, "anchor_total": 100.0},
        {"cash": "currency", "anchor_total": "currency"},
    ),
    ScalarFormula(
        "sale_cost",
        "預期成交價格",
        "m+\\delta\\sum_bP(sale>b)",
        "currency",
        ("market.volatility",),
        scalar.sale_cost,
        {"minimum": 1.0, "increment": 1.0, "survival": (0.8, 0.4)},
        {"minimum": "currency", "increment": "currency", "survival": "probability"},
    ),
    ScalarFormula(
        "winning_cost",
        "預期贏標成本",
        "m+\\delta[\\sum_bP(foe>b)+P(foe>m)]",
        "currency",
        ("market.volatility",),
        scalar.winning_cost,
        {"minimum": 1.0, "increment": 1.0, "survival": (0.8, 0.4)},
        {"minimum": "currency", "increment": "currency", "survival": "probability"},
    ),
    ScalarFormula(
        "planning_cost",
        "離散組隊成本",
        "\\max(m,\\delta\\lfloor cost/\\delta+1/2\\rfloor)",
        "currency",
        (),
        scalar.planning_cost,
        {"minimum": 1.0, "increment": 2.0, "acquisition": 5.2},
        {"minimum": "currency", "increment": "currency", "acquisition": "currency"},
    ),
    ScalarFormula(
        "affordable_cap",
        "組隊停損價",
        "\\delta\\lfloor\\min(B-(R-1)m,B-C_{rest})/\\delta\\rfloor",
        "currency",
        (),
        scalar.affordable_cap,
        {
            "budget": 40.0,
            "slots": 3.0,
            "minimum": 1.0,
            "completion_cost": 15.0,
            "increment": 1.0,
        },
        {
            "budget": "currency",
            "slots": "players",
            "minimum": "currency/player",
            "completion_cost": "currency",
            "increment": "currency",
        },
    ),
    ScalarFormula(
        "second_price",
        "次高出價成交金額",
        r"P=\min(B_{winner}, B_{runner}+\delta)",
        "auction dollars",
        (),
        scalar.second_price,
        {"winner": 10.0, "runner_up": 7.0, "increment": 1.0},
        {"winner": "winning bid", "runner_up": "runner-up bid", "increment": "legal bid increment"},
    ),
    ScalarFormula(
        "anchor_scale",
        "受出價上下限約束的公開估值縮放",
        r"\sum_i\operatorname{clip}_{[m,M]}(sQ_i)=\min(C,\sum_i U_i)",
        "auction price scale",
        (),
        scalar.anchor_scale,
        {"quotes": (10.0, 20.0), "cash": 30.0, "minimum": 1.0, "maximum": 25.0},
        {
            "quotes": "public price quotes",
            "cash": "available auction cash",
            "minimum": "minimum bid",
            "maximum": "maximum legal bid",
        },
    ),
    ScalarFormula(
        "minute_budget",
        "球隊每場分鐘預算",
        "M=P(R+O)",
        "minutes",
        (),
        scalar.minute_budget,
        {"players": 5.0, "regulation": 48.0, "overtime": 2.0},
        {
            "players": "players on court",
            "regulation": "regulation minutes",
            "overtime": "expected overtime minutes",
        },
    ),
    ScalarFormula(
        "season_rate",
        "每場球隊平均球員貢獻",
        "R=Gv/N",
        "contribution per team game",
        (),
        scalar.season_rate,
        {"games": 41.0, "value": 30.0, "season_games": 82.0},
        {
            "games": "expected player games",
            "value": "per-player game contribution",
            "season_games": "full season team games",
        },
    ),
)
