"""Single catalog of scalar formula metadata and executable examples."""

from fba.contracts.formula import ScalarFormula
from fba.formulas import scalar

FORMULAS = (
    ScalarFormula(
        "weighted_mean",
        "加權平均",
        r"\bar x=\sum_iw_ix_i/\sum_iw_i",
        "input units",
        (),
        scalar.weighted_mean,
        {"values": (1.0, 3.0), "weights": (1.0, 3.0)},
        {"values": "input units", "weights": "sample count"},
    ),
    ScalarFormula(
        "complementarity",
        "類別需求互補分數",
        r"S=-\sum_c(p_c-0.5)(q_c-0.5)",
        "complementarity score",
        (),
        scalar.complementary_value,
        {"home": (0.75, 0.25), "away": (0.25, 0.75)},
        {"home": "category probability", "away": "category probability"},
    ),
    ScalarFormula(
        "path_bid",
        "競標路徑實際出價",
        r"b=\delta\lfloor\min(B,m+\max(0,a-m)\,I\,r\,t\,u)/\delta\rfloor",
        "currency",
        ("market.volatility", "stress.premium_multiplier"),
        scalar.path_bid,
        {
            "minimum": 1.0,
            "anchor": 5.0,
            "inflation": 1.5,
            "participation": 1.0,
            "taste": 1.0,
            "premium": 1.0,
            "maximum": 6.0,
            "increment": 1.0,
        },
        {
            "minimum": "currency",
            "anchor": "currency",
            "inflation": "multiplier",
            "participation": "multiplier",
            "taste": "multiplier",
            "premium": "multiplier",
            "maximum": "currency",
            "increment": "currency",
        },
    ),
    ScalarFormula(
        "historical_share",
        "歷史比例補齊預測",
        r"x=P\,N/D",
        "count",
        ("preparation.history_shares",),
        scalar.historical_share,
        {"parent": 20.0, "numerator": 2.0, "denominator": 5.0},
        {"parent": "count", "numerator": "count", "denominator": "count"},
    ),
    ScalarFormula(
        "rank_correlation",
        "含同分平均排名的 Spearman 相關",
        r"\rho=\frac{\sum_i(R_i-\bar R)(S_i-\bar S)}"
        r"{\sqrt{\sum_i(R_i-\bar R)^2\sum_i(S_i-\bar S)^2}}",
        "correlation",
        (),
        scalar.rank_correlation,
        {"predicted": (1.0, 2.0, 3.0), "observed": (3.0, 2.0, 1.0)},
        {"predicted": "ranking values", "observed": "ranking values"},
    ),
    ScalarFormula(
        "median",
        "觀測中位數",
        r"median(x)=x_{middle}\;\text{or}\;(x_{left}+x_{right})/2",
        "input units",
        (),
        scalar.median,
        {"values": (1.0, 3.0, 2.0, 4.0)},
        {"values": "input units"},
    ),
    ScalarFormula(
        "healthy_capacity",
        "可健康出賽場數",
        r"G_H=\min(G_E,\max(G,G_E-(G_E-G)s))",
        "games",
        ("health.injury_share",),
        scalar.healthy_capacity,
        {"expected": 40.0, "eligible": 60.0, "injury_share": 0.5},
        {"expected": "games", "eligible": "games", "injury_share": "absence fraction"},
    ),
    ScalarFormula(
        "clipped_affine",
        "有界線性校正",
        r"y=\min(u,\max(l,a+bx))",
        "input units",
        (),
        scalar.clipped_affine,
        {"value": 10.0, "intercept": 2.0, "slope": 0.5, "lower": 0.0, "upper": 20.0},
        {
            "value": "input units",
            "intercept": "input units",
            "slope": "coefficient",
            "lower": "input units",
            "upper": "input units",
        },
    ),
    ScalarFormula(
        "budget_fraction",
        "需求預算分配比例",
        r"f=\min(1,B/D),\quad D=0\Rightarrow f=1",
        "fraction",
        (),
        scalar.budget_fraction,
        {"budget": 8.0, "demand": 10.0},
        {"budget": "resource units", "demand": "resource units"},
    ),
    ScalarFormula(
        "market_normalization",
        "第二高競價期望正規化",
        r"a=\log\int e^{\sigma z}n(n-1)\Phi(z)^{n-2}[1-\Phi(z)]\phi(z)\,dz",
        "log bid multiplier",
        ("market.volatility",),
        scalar.market_normalization,
        {"teams": 2.0, "volatility": 0.0},
        {"teams": "bidders", "volatility": "log bid standard deviation"},
    ),
    ScalarFormula(
        "empirical_error",
        "觀測樣本平均值標準誤",
        r"SE=\sqrt{\sum_i(x_i-\bar x)^2/[n(n-1)]}",
        "observation units",
        (),
        scalar.empirical_error,
        {"values": (2.0, 4.0)},
        {"values": "observation units"},
    ),
    ScalarFormula(
        "blend",
        "先驗與樣本混合",
        r"(k r_0+C)/(k+M)",
        "output=input/sample",
        ("rate_k", "shot_k"),
        scalar.blend,
        {"k": 300.0, "prior": 0.52, "total": 412.0, "sample": 780.0},
        {
            "k": "prior exposure",
            "prior": "count/exposure",
            "total": "count",
            "sample": "observed exposure",
        },
    ),
    ScalarFormula(
        "minutes",
        "時間加權分鐘",
        r"(k_g m_0+\sum_j 0.5^{(n-j)/h}m_j)/(k_g+\sum_j 0.5^{(n-j)/h})",
        "minutes/game",
        ("minute_k", "minute_half_life"),
        scalar.minutes,
        {"k": 3.0, "prior": 30.0, "minutes": (20.0, 40.0), "half_life": 10.0},
        {
            "k": "games",
            "prior": "minutes/game",
            "minutes": "minutes/game",
            "half_life": "games",
        },
    ),
    ScalarFormula(
        "weight",
        "當季權重",
        r"M/(M+k)",
        "fraction",
        ("rate_k", "shot_k"),
        scalar.sample_weight,
        {"sample": 100.0, "k": 300.0},
        {"sample": "observed exposure", "k": "prior exposure"},
    ),
    ScalarFormula(
        "expectation",
        "每場預期",
        r"q r m",
        "count/game",
        ("availability",),
        scalar.expectation,
        {"q": 0.8, "rate": 0.5, "minutes": 30.0},
        {"q": "probability", "rate": "count/minute", "minutes": "minutes/game"},
    ),
    ScalarFormula(
        "calibration",
        "機率校準",
        r"0.5+c(p-0.5)",
        "probability",
        ("calibration",),
        scalar.shrink,
        {"p": 0.9, "c": 0.8},
        {"p": "probability", "c": "dimensionless"},
    ),
    ScalarFormula(
        "score_calibration",
        "本週分數校準",
        r"S/2+c(x-S/2)",
        "score",
        ("calibration",),
        scalar.score_calibration,
        {"score": 6.0, "scale": 9.0, "c": 0.8},
        {"score": "score", "scale": "maximum score", "c": "dimensionless"},
    ),
    ScalarFormula(
        "z",
        "常態近似",
        r"(\mu_h-\mu_a)/\sqrt{v_h+v_a}",
        "standard deviations",
        ("tolerance",),
        scalar.z_score,
        {"home": 12.0, "away": 10.0, "home_variance": 1.0, "away_variance": 3.0, "limit": 10.0},
        {
            "home": "category units",
            "away": "category units",
            "home_variance": "squared category units",
            "away_variance": "squared category units",
            "limit": "standard deviations",
        },
    ),
    ScalarFormula(
        "normal",
        "常態累積機率",
        r"\Phi(z)=(1+\operatorname{erf}(z/\sqrt2))/2",
        "probability",
        (),
        scalar.normal_probability,
        {"z": 0.0},
        {"z": "standard deviations"},
    ),
    ScalarFormula(
        "error",
        "模擬標準誤",
        r"\sqrt{\operatorname{Var}(X)/N}",
        "score",
        ("simulations",),
        scalar.sampling_error,
        {"variance": 0.25, "samples": 100.0},
        {"variance": "squared score units", "samples": "simulations"},
    ),
    ScalarFormula(
        "probability",
        "模擬勝率",
        r"(W+tT)/N",
        "probability",
        (),
        scalar.probability,
        {"wins": 60.0, "ties": 10.0, "tie": 0.5, "samples": 100.0},
        {
            "wins": "simulations",
            "ties": "simulations",
            "tie": "score/tie",
            "samples": "simulations",
        },
    ),
    ScalarFormula(
        "add_score",
        "換人分數",
        r"\Delta P+\lambda\Delta E",
        "wins",
        (),
        scalar.add_score,
        {"delta_week": 0.1, "delta_season": 0.2, "weight": 1.0},
        {
            "delta_week": "weekly score",
            "delta_season": "expected season wins",
            "weight": "weekly score/season win",
        },
    ),
    ScalarFormula(
        "difference",
        "改變量",
        r"after-before",
        "same as inputs",
        (),
        scalar.difference,
        {"after": 0.7, "before": 0.5},
        {"after": "result units", "before": "result units"},
    ),
    ScalarFormula(
        "rank_value",
        "公開排名價值",
        r"scale/rank^{exponent}",
        "public value",
        ("rank_scale", "rank_exponent"),
        scalar.rank_value,
        {"scale": 100.0, "rank": 10.0, "exponent": 1.0},
        {"scale": "public value", "rank": "ordinal rank", "exponent": "dimensionless"},
    ),
    ScalarFormula(
        "acceptance",
        "接受機率",
        r"\sigma((\beta_R\Delta R+\beta_N\Delta N-\theta)/s)",
        "probability",
        ("beta_rank", "beta_need", "acceptance_threshold", "acceptance_noise"),
        scalar.acceptance,
        {
            "beta_rank": 1.0,
            "beta_need": 1.0,
            "delta_rank": 0.0,
            "delta_need": 0.0,
            "threshold": 0.0,
            "noise": 1.0,
        },
        {
            "beta_rank": "latent value/public value",
            "beta_need": "latent value/need unit",
            "delta_rank": "public value",
            "delta_need": "need units",
            "threshold": "latent value",
            "noise": "latent value",
        },
    ),
    ScalarFormula(
        "product",
        "係數加權",
        r"x\,w",
        "same as gain",
        (),
        scalar.product,
        {"gain": 0.4, "probability": 0.5},
        {"gain": "input units", "probability": "dimensionless weight"},
    ),
    ScalarFormula(
        "brier",
        "Brier",
        r"N^{-1}\sum_i(p_i-y_i)^2",
        "squared probability",
        (),
        scalar.brier,
        {"predicted": (0.2, 0.8), "observed": (0.0, 1.0)},
        {"predicted": "probability", "observed": "outcome score"},
    ),
    ScalarFormula(
        "log_loss",
        "Log loss",
        r"-N^{-1}\sum_i[y_i\log p_i+(1-y_i)\log(1-p_i)]",
        "nats",
        ("tolerance",),
        scalar.log_loss,
        {"predicted": (0.5,), "observed": (1.0,), "epsilon": 0.000001},
        {"predicted": "probability", "observed": "outcome score", "epsilon": "probability"},
    ),
    ScalarFormula(
        "mae",
        "平均絕對誤差",
        r"N^{-1}\sum_i|p_i-y_i|",
        "input units",
        (),
        scalar.mean_absolute_error,
        {"predicted": (2.0, 4.0), "observed": (1.0, 3.0)},
        {"predicted": "result units", "observed": "result units"},
    ),
    ScalarFormula(
        "reallocate",
        "分鐘重分配",
        r"m_i-\Delta m\,m_i/\sum m",
        "minutes/game",
        (),
        scalar.reallocate,
        {"current": 30.0, "delta": 10.0, "team_total": 100.0},
        {"current": "minutes/game", "delta": "minutes/game", "team_total": "minutes/game"},
    ),
    ScalarFormula(
        "linear",
        "總量加權",
        r"\sum_i a_i x_i",
        "output units",
        (),
        scalar.weighted_sum,
        {"values": (2.0, 3.0), "weights": (1.0, 2.0)},
        {"values": "statistic units", "weights": "output units/statistic unit"},
    ),
    ScalarFormula(
        "ratio",
        "數量比值",
        r"N/D\;(D\ne0),\quad r_0\;(D=0)",
        "numerator units / denominator units",
        (),
        scalar.total_ratio,
        {"numerator": 3.0, "denominator": 4.0, "zero_value": 0.0},
        {
            "numerator": "numerator units",
            "denominator": "denominator units",
            "zero_value": "numerator units / denominator units",
        },
    ),
    ScalarFormula(
        "threshold",
        "逐場門檻計數",
        r"\mathbf1[\sum_i\mathbf1[x_i\ge t]\ge h]",
        "games",
        (),
        scalar.threshold_count,
        {"values": (10.0, 12.0, 3.0), "threshold": 10.0, "minimum_hits": 2.0},
        {"values": "count/game", "threshold": "count/game", "minimum_hits": "statistics"},
    ),
    ScalarFormula(
        "mean",
        "算術平均",
        "\\frac{1}{n}\\sum_i x_i",
        "input units",
        (),
        scalar.mean,
        {"values": (2.0, 4.0)},
        {"values": "input units"},
    ),
    ScalarFormula(
        "variance",
        "母體變異數",
        "\\frac{1}{n}\\sum_i(x_i-\\mu)^2",
        "squared input units",
        (),
        scalar.population_variance,
        {"values": (2.0, 4.0), "mean": 3.0},
        {"values": "input units", "mean": "input units"},
    ),
    ScalarFormula(
        "standardize",
        "類別標準化",
        "(x-\\mu)/\\sigma",
        "standard deviations",
        (),
        scalar.standardize,
        {"value": 8.0, "mean": 4.0, "deviation": 2.0},
        {"value": "category impact", "mean": "category impact", "deviation": "category impact"},
    ),
    ScalarFormula(
        "ratio_impact",
        "比率類別總量影響",
        "d(made-r_{pool}attempted)",
        "direction-adjusted count",
        (),
        scalar.ratio_impact,
        {"direction": 1.0, "made": 6.0, "rate": 0.5, "attempted": 10.0},
        {"direction": "sign", "made": "count", "rate": "ratio", "attempted": "count"},
    ),
    ScalarFormula(
        "season_utility",
        "替補以上賽季效用",
        "(\\sum_c z_c-z_{replacement})G/G_{season}",
        "utility",
        ("valuation.healthy_games", "valuation.replacement_count"),
        scalar.season_utility,
        {"scores": (1.0, 2.0), "replacement": 1.0, "games": 40.0, "season_games": 80.0},
        {
            "scores": "standard deviations",
            "replacement": "standard deviations",
            "games": "games",
            "season_games": "games",
        },
    ),
    ScalarFormula(
        "dollar_scale",
        "聯盟效用金額換算",
        "(TB-Nm)/\\sum_{i\\in drafted}u_i^+",
        "currency/utility",
        (),
        scalar.dollar_scale,
        {
            "teams": 2.0,
            "budget": 100.0,
            "roster_count": 4.0,
            "minimum": 1.0,
            "positive_utilities": (1.0, 1.0, 2.0, 3.0),
        },
        {
            "teams": "teams",
            "budget": "currency/team",
            "roster_count": "players",
            "minimum": "currency/player",
            "positive_utilities": "utility",
        },
    ),
    ScalarFormula(
        "dollar_value",
        "公允價格",
        "\\mathbf1[u>0](m+uS)",
        "currency",
        (),
        scalar.dollar_value,
        {"utility": 2.0, "minimum": 1.0, "scale": 28.0},
        {"utility": "utility", "minimum": "currency", "scale": "currency/utility"},
    ),
    ScalarFormula(
        "bidder_wealth",
        "買家剩餘購買力",
        "\\operatorname{clip}((B/R-m)/\\bar{s},l,h)^e",
        "wealth multiplier",
        ("market.wealth_lower", "market.wealth_upper", "market.wealth_exponent"),
        scalar.bidder_wealth,
        {
            "budget": 30.0,
            "slots": 3.0,
            "minimum": 1.0,
            "average_surplus": 6.0,
            "lower": 0.5,
            "upper": 2.0,
            "exponent": 1.0,
        },
        {
            "budget": "currency",
            "slots": "players",
            "minimum": "currency/player",
            "average_surplus": "currency/player",
            "lower": "multiplier",
            "upper": "multiplier",
            "exponent": "dimensionless",
        },
    ),
    ScalarFormula(
        "anchor",
        "有上下界的市場錨點",
        "quote\\ge cutoff?\\operatorname{clip}(quote\\,scale,min,max):min",
        "currency",
        (),
        scalar.clipped_anchor,
        {"quote": 10.0, "scale": 2.0, "minimum": 1.0, "maximum": 15.0, "cutoff": 5.0},
        {
            "quote": "currency",
            "scale": "multiplier",
            "minimum": "currency",
            "maximum": "currency",
            "cutoff": "currency",
        },
    ),
    ScalarFormula(
        "inflation",
        "剩餘市場通膨",
        "cash/\\sum anchor",
        "multiplier",
        (),
        scalar.market_inflation,
        {"cash": 120.0, "anchor_total": 100.0},
        {"cash": "currency", "anchor_total": "currency"},
    ),
    ScalarFormula(
        "sale_cost",
        "預期成交價格",
        "m+\\delta\\sum_bP(sale>b)",
        "currency",
        ("market.volatility",),
        scalar.sale_cost,
        {"minimum": 1.0, "increment": 1.0, "survival": (0.8, 0.4)},
        {"minimum": "currency", "increment": "currency", "survival": "probability"},
    ),
    ScalarFormula(
        "winning_cost",
        "預期贏標成本",
        "m+\\delta[\\sum_bP(foe>b)+P(foe>m)]",
        "currency",
        ("market.volatility",),
        scalar.winning_cost,
        {"minimum": 1.0, "increment": 1.0, "survival": (0.8, 0.4)},
        {"minimum": "currency", "increment": "currency", "survival": "probability"},
    ),
    ScalarFormula(
        "planning_cost",
        "離散組隊成本",
        "\\max(m,\\delta\\lfloor cost/\\delta+1/2\\rfloor)",
        "currency",
        (),
        scalar.planning_cost,
        {"minimum": 1.0, "increment": 2.0, "acquisition": 5.2},
        {"minimum": "currency", "increment": "currency", "acquisition": "currency"},
    ),
    ScalarFormula(
        "affordable_cap",
        "組隊停損價",
        "\\delta\\lfloor\\min(B-(R-1)m,B-C_{rest})/\\delta\\rfloor",
        "currency",
        (),
        scalar.affordable_cap,
        {
            "budget": 40.0,
            "slots": 3.0,
            "minimum": 1.0,
            "completion_cost": 15.0,
            "increment": 1.0,
        },
        {
            "budget": "currency",
            "slots": "players",
            "minimum": "currency/player",
            "completion_cost": "currency",
            "increment": "currency",
        },
    ),
)
