"""Simulation formula metadata, examples and units."""

from fba.formulas import lineup, simulation
from fba.formulas.array_catalog import ArrayFormula

ARRAY_FORMULAS = (
    ArrayFormula(
        "accumulation_error",
        "固定加總浮點誤差上界",
        r"E=n\,ulp(2\sum_i |x_i|)\quad\text{(outward rounded)}",
        "input units",
        (),
        lineup.accumulation_error,
        {"magnitude": (1.0, 8.0), "additions": 4.0},
        {"magnitude": "absolute sum upper bound", "additions": "maximum additions"},
    ),
    ArrayFormula(
        "threshold_accumulate",
        "有固定誤差界限的門檻差累加",
        r"M'=M+X",
        "numerator units",
        (),
        lineup.threshold_accumulate,
        {"base": (1.0, -2.0), "draw": (2.0, 3.0)},
        {"base": "accumulated margin bound", "draw": "margin contribution"},
    ),
    ArrayFormula(
        "comparison_thresholds",
        "捨入比較的必要門檻",
        r"T_{tie},T_{win}: round(x,k)<round(a,k),\;round(x,k)\le round(a,k)",
        "directed category units",
        (),
        lineup.comparison_thresholds,
        {"away": (0.45, 0.8), "decimals": 3.0},
        {"away": "directed opponent value", "decimals": "comparison decimal places"},
    ),
    ArrayFormula(
        "linear_roundoff",
        "樣本累加與類別加權的浮點誤差上界",
        r"E\ge\sum_s |w_s|n\,ulp(2U_s)+(2m+1)ulp(\sum_s|w_s|2U_s)",
        "category total units",
        (),
        lineup.linear_roundoff,
        {"upper": ((5.0, 8.0),), "additions": 4.0, "indices": (0.0, 1.0), "weights": (2.0, -1.0)},
        {
            "upper": "nonnegative total bound",
            "additions": "addition count",
            "indices": "statistic axis indices",
            "weights": "configured coefficients",
        },
    ),
    ArrayFormula(
        "threshold_margin",
        "保留比率相關性的門檻差上界",
        r"M=N_u-\min(TD_l,TD_u)\quad\text{(outward rounded)}",
        "numerator units",
        (),
        lineup.threshold_margin,
        {"upper": (4.0,), "dlower": (6.0,), "dupper": (6.0,), "threshold": ((0.4, 0.5),)},
        {
            "upper": "directed numerator upper bound",
            "dlower": "denominator lower bound",
            "dupper": "denominator upper bound",
            "threshold": "tie and win thresholds",
        },
    ),
    ArrayFormula(
        "threshold_error",
        "比率門檻差的浮點誤差上界",
        r"E=E_N+|T|E_D\quad\text{(outward rounded)}",
        "numerator units",
        (),
        lineup.threshold_error,
        {"numerator": (1e-12,), "denominator": (2e-12,), "threshold": ((0.4, 0.5),)},
        {
            "numerator": "numerator error",
            "denominator": "denominator error",
            "threshold": "tie and win thresholds",
        },
    ),
    ArrayFormula(
        "threshold_votes",
        "完整搜尋的類別結果上界",
        r"V=\max(V_0,1\;(M_w+E_w\ge0),0\;(M_t+E_t\ge0),-1)",
        "category sign",
        (),
        lineup.threshold_votes,
        {"upper": ((1.0, -1.0),), "error": ((0.0, 0.0),), "zero_votes": (-1.0,)},
        {
            "upper": "tie and win margin upper bounds",
            "error": "margin error bounds",
            "zero_votes": "zero denominator outcome bound",
        },
    ),
    ArrayFormula(
        "strict_win",
        "整週嚴格勝出的樣本",
        r"W=\mathbf1[P_H=1\land P_A<1]",
        "win indicator",
        (),
        simulation.strict_win,
        {"own": (1.0, 0.5, 0.0, 1.0), "other": (0.0, 0.5, 1.0, 1.0)},
        {"own": "standings credit", "other": "standings credit"},
    ),
    ArrayFormula(
        "nested_count_limit",
        "子計數不超過母計數",
        r"C'=\min(C,P)",
        "count",
        (),
        simulation.nested_count_limit,
        {"child": (4.0, 2.0, 0.0), "parent": (3.0, 5.0, 0.0)},
        {"child": "count", "parent": "count"},
    ),
    ArrayFormula(
        "array_product",
        "樣本與設定倍率的乘積",
        r"y=xw",
        "scaled input units",
        (),
        simulation.array_product,
        {"values": ((2.0, 3.0), (5.0, 1.0)), "multiplier": (2.0, -1.0)},
        {"values": "input units", "multiplier": "multiplier"},
    ),
    ArrayFormula(
        "nonnegative_samples",
        "模擬總量的非負截取",
        r"x^+=\max(x,0)",
        "statistic units",
        (),
        simulation.nonnegative_samples,
        {"values": (-2.0, -0.0, 3.0)},
        {"values": "statistic units"},
    ),
    ArrayFormula(
        "derived_sum",
        "衍生數據項目加總",
        r"d=\operatorname{sum}_{last}(x)",
        "derived statistic units",
        (),
        simulation.derived_sum,
        {"values": ((4.0, -3.0), (10.0, -1.0))},
        {"values": "derived statistic terms"},
    ),
    ArrayFormula(
        "health_step",
        "健康狀態的單場轉移",
        r"H'=I(U\ge h)\;(H=1);\quad H'=I(U<b)\;(H=0)",
        "boolean",
        ("fit.mean_missed_games",),
        simulation.health_step,
        {"health": (1.0, 0.0, 1.0), "uniform": (0.8, 0.2, 0.1), "hurt": 0.25, "back": 0.4},
        {
            "health": "boolean",
            "uniform": "uniform coordinate",
            "hurt": "probability",
            "back": "probability",
        },
    ),
    ArrayFormula(
        "subset_bound",
        "可選樣本加總的保守界限",
        r"B'=nextafter(B+C,\pm\infty),\quad C=X\;(fixed),\;\min(X,0)\;(lower),\;\max(X,0)\;(upper)",
        "statistic units",
        (),
        simulation.subset_bound,
        {"base": (1.0, 5.0), "draw": (2.0, -3.0), "fixed": 0.0, "direction": -1.0},
        {
            "base": "statistic units",
            "draw": "statistic units",
            "fixed": "boolean",
            "direction": "signed bound direction",
        },
    ),
    ArrayFormula(
        "outward_bound",
        "浮點界限向外捨入",
        r"B'=nextafter(B,\pm\infty)",
        "statistic units",
        (),
        simulation.outward_bound,
        {"value": (1.0, -2.0), "direction": 1.0},
        {"value": "statistic units", "direction": "signed bound direction"},
    ),
    ArrayFormula(
        "sample_mean",
        "模擬樣本平均",
        "\\mu=\\operatorname{mean}_{A}(x)",
        "observation units",
        (),
        simulation.sample_mean,
        {"values": ((1.0, 3.0), (3.0, 7.0)), "axes": (0.0,)},
        {"values": "observation units", "axes": "reduction axis indices"},
    ),
    ArrayFormula(
        "sample_variance",
        "模擬樣本母體變異",
        "v=\\operatorname{mean}_{A}((x-\\mu)^2)",
        "squared observation units",
        (),
        simulation.sample_variance,
        {"values": ((1.0, 3.0), (3.0, 7.0)), "axes": (0.0,)},
        {"values": "observation units", "axes": "reduction axis indices"},
    ),
    ArrayFormula(
        "sample_deviation",
        "模擬樣本標準差",
        "s=\\sqrt{\\operatorname{mean}_{A}((x-\\mu)^2)}",
        "observation units",
        (),
        simulation.sample_deviation,
        {"values": ((1.0, 3.0), (3.0, 7.0)), "axes": (0.0,)},
        {"values": "observation units", "axes": "reduction axis indices"},
    ),
    ArrayFormula(
        "linear_totals",
        "設定類別總量",
        "T=\\sum_s x_s w_s",
        "configured category units",
        (),
        simulation.linear_totals,
        {"values": ((2.0, 3.0), (5.0, 1.0)), "weights": (2.0, -1.0), "indices": (0.0, 1.0)},
        {
            "values": "statistic totals",
            "weights": "configured coefficients",
            "indices": "statistic axis indices",
        },
    ),
    ArrayFormula(
        "category_ratio",
        "設定比率類別總量",
        "R=N/D\\ (D>0),\\quad R=R_0\\ (D\\leq0)",
        "configured ratio units",
        (),
        simulation.category_ratio,
        {"numerator": (6.0, 3.0), "denominator": (2.0, 0.0), "zero_value": (0.0, 3.0)},
        {
            "numerator": "numerator total",
            "denominator": "denominator total",
            "zero_value": "configured zero-denominator value",
        },
    ),
    ArrayFormula(
        "game_threshold",
        "逐場達標統計",
        "I=\\mathbf{1}[\\sum_s\\mathbf{1}[x_s\\geq t]\\geq h]",
        "game indicator",
        (),
        simulation.game_threshold,
        {"values": ((10.0, 9.0, 12.0), (5.0, 6.0, 10.0)), "threshold": 10.0, "minimum_hits": 2.0},
        {
            "values": "weighted game statistics",
            "threshold": "statistic threshold",
            "minimum_hits": "required qualifying statistics",
        },
    ),
    ArrayFormula(
        "comparison_margin",
        "類別精度比較差",
        "d=\\operatorname{round}(a,k)-\\operatorname{round}(b,k)",
        "configured category units",
        (),
        simulation.comparison_margin,
        {"home": (1.234, 5.0), "away": (1.231, 3.0), "decimals": 2.0},
        {
            "home": "directed home category value",
            "away": "directed away category value",
            "decimals": "comparison decimal places",
        },
    ),
    ArrayFormula(
        "linear_interval",
        "類別總量保守區間",
        "[L,U]=\\sum_s w_s[l_s,u_s]\\quad\\text{(outward rounded)}",
        "configured category units",
        (),
        simulation.linear_interval,
        {
            "lower": ((1.0, 2.0),),
            "upper": ((3.0, 4.0),),
            "weights": (2.0, -1.0),
            "indices": (0.0, 1.0),
        },
        {
            "lower": "lower statistic bounds",
            "upper": "upper statistic bounds",
            "weights": "configured coefficients",
            "indices": "statistic axis indices",
        },
    ),
    ArrayFormula(
        "ratio_interval",
        "比率類別保守區間",
        "[L,U]=[\\min(N/D),\\max(N/D)]\\quad D\\in[D_l,D_u]",
        "configured ratio units",
        (),
        simulation.ratio_interval,
        {"lower": (2.0,), "upper": (6.0,), "dlower": (2.0,), "dupper": (4.0,)},
        {
            "lower": "lower numerator bound",
            "upper": "upper numerator bound",
            "dlower": "lower denominator bound",
            "dupper": "upper denominator bound",
        },
    ),
    ArrayFormula(
        "standings_credit",
        "已入帳戰績積分",
        "S=W+tT",
        "standings points",
        (),
        simulation.standings_credit,
        {"wins": (3.0, 4.0), "ties": (2.0, 1.0), "tie_value": 0.5},
        {
            "wins": "completed wins",
            "ties": "completed ties",
            "tie_value": "configured points per tied matchup",
        },
    ),
    ArrayFormula(
        "playoff_odds",
        "模擬晉級機率",
        "p_i=\\operatorname{mean}_j\\mathbf{1}[\\operatorname{rank}(S_{ij},\\text{seed},i)<K]",
        "probability",
        ("tolerance",),
        simulation.playoff_odds,
        {"scores": ((3.0, 4.0), (4.0, 3.0)), "seeds": (1.0, 2.0), "tolerance": 0.01, "places": 1.0},
        {
            "scores": "team by sample standings points",
            "seeds": "existing tie-break seed",
            "tolerance": "score comparison tolerance",
            "places": "configured playoff places",
        },
    ),
    ArrayFormula(
        "lognormal_taste",
        "競標偏好抽樣變換",
        "T=\\exp(vZ-b)",
        "relative bid multiplier",
        (),
        simulation.lognormal_taste,
        {"normal_draws": (0.0, 1.0), "volatility": 1.0, "shift": 0.0},
        {
            "normal_draws": "standard normal draws",
            "volatility": "log multiplier standard deviation",
            "shift": "normalization in log units",
        },
    ),
    ArrayFormula(
        "health_decay",
        "出賽狀態衰減",
        "d_g=\\prod_{h=1}^g(1-b_h-i_h),\\quad d_0=1",
        "health-state correlation",
        (),
        simulation.health_decay,
        {"back": (0.25,), "hurt": (0.25,), "steps": 2.0},
        {
            "back": "return probability",
            "hurt": "injury probability",
            "steps": "game-clock transition count",
        },
    ),
    ArrayFormula(
        "control_covariance",
        "健康控制變量共變異修正",
        "C=\\sum_i(q_i-\\overline{H_i})\\Sigma_i",
        "squared statistic units",
        (),
        simulation.control_covariance,
        {"availability": (0.75,), "health": ((1.0,), (0.0,)), "covariance": (((4.0,),),)},
        {
            "availability": "healthy probability",
            "health": "health sample by player indicator",
            "covariance": "per-player statistic covariance",
        },
    ),
    ArrayFormula(
        "normal_quantile",
        "標準常態反分位數",
        "Z=\\Phi^{-1}(\\operatorname{clip}_{[\\epsilon,1-\\epsilon]}U)",
        "standard deviations",
        (),
        simulation.normal_quantile,
        {"uniform": (0.5, 0.8413447460685429), "epsilon": 1e-12},
        {"uniform": "uniform quantiles", "epsilon": "endpoint clipping probability"},
    ),
    ArrayFormula(
        "scheduled_health",
        "賽程加權可出賽場數",
        "G_i=\\sum_d S_{di}q_{di}",
        "expected games",
        (),
        simulation.scheduled_health,
        {"scheduled": ((1.0, 0.0), (1.0, 1.0)), "probabilities": ((0.5, 0.5), (0.5, 0.5))},
        {
            "scheduled": "day by player game indicator",
            "probabilities": "day by player healthy probability",
        },
    ),
    ArrayFormula(
        "ranked_health_value",
        "健康狀態下的排陣價值",
        "V_i=v_i[H_ir_i^h+(1-H_i)r_i^u]",
        "utility",
        (),
        simulation.ranked_health_value,
        {
            "health": (1.0, 0.0),
            "healthy": (2.0, 3.0),
            "unhealthy": (0.0, -1.0),
            "value": (2.0, 2.0),
        },
        {
            "health": "healthy indicator",
            "healthy": "healthy rank weight",
            "unhealthy": "unhealthy rank weight",
            "value": "per-player value",
        },
    ),
    ArrayFormula(
        "portfolio_cost_floor",
        "指定球員組隊成本保守下界",
        "L(\\lambda)=\\lambda(V-v_i)-\\sum_{j\\in\\operatorname{top}_{R-1}}(\\lambda v_j-c_j)",
        "auction dollars",
        ("model.portfolio.bound_multipliers", "model.portfolio.value_tolerance"),
        simulation.portfolio_cost_floor,
        {
            "values": (1.0, 3.0),
            "costs": (2.0, 4.0),
            "indices": (0.0, 1.0),
            "multipliers": (1.0,),
            "slots": 1.0,
            "player": 0.0,
            "target": 4.0,
            "player_value": 1.0,
            "tolerance": 0.0,
        },
        {
            "values": "candidate utility",
            "costs": "candidate acquisition dollars",
            "indices": "candidate player axis indices",
            "multipliers": "configured Lagrange multiplier grid before range scaling",
            "slots": "remaining roster slots",
            "player": "forced player axis index",
            "target": "target roster utility",
            "player_value": "forced player utility",
            "tolerance": "utility comparison tolerance",
        },
    ),
    ArrayFormula(
        "highest_bid_survival",
        "最高對手出價存活機率",
        "P(\\max B_j>b)=1-\\prod_j F_j(b)",
        "probability",
        (),
        simulation.highest_bid_survival,
        {"cdf": ((0.5, 1.0), (0.5, 1.0))},
        {"cdf": "opponent by bid-level cumulative probabilities"},
    ),
    ArrayFormula(
        "median_bid",
        "離散出價中位數",
        "B_{.5}=\\delta\\lfloor\\min(M,m+p e^{-b})/\\delta\\rfloor",
        "auction dollars",
        (),
        simulation.median_bid,
        {"maximum": (10.0,), "minimum": 1.0, "premium": (4.0,), "shift": 0.0, "increment": 2.0},
        {
            "maximum": "maximum bid dollars",
            "minimum": "minimum bid dollars",
            "premium": "bid premium dollars",
            "shift": "log normalization",
            "increment": "legal bid increment dollars",
        },
    ),
)
