import numpy as np
from numpy.typing import NDArray
def expit(x: NDArray[np.float64]) -> NDArray[np.float64]: ...

def log_ndtr(x: float) -> float: ...
def ndtr(x: NDArray[np.float64]) -> NDArray[np.float64]: ...
