import numpy as np
from numpy.typing import NDArray
class Sobol:
    def __init__(self, d: int, *, scramble: bool, seed: int | np.random.Generator) -> None: ...
    def random_base2(self, m: int) -> NDArray[np.float64]: ...
